/** Central query keys so realtime events can invalidate the right caches. */
export const qk = {
  me: ['me'] as const,
  dashboard: ['dashboard'] as const,
  complaints: ['complaints'] as const,
  complaintList: (params: Record<string, unknown>) => ['complaints', 'list', params] as const,
  complaint: (id: string) => ['complaints', 'detail', id] as const,
  nearby: (params: Record<string, unknown>) => ['complaints', 'nearby', params] as const,
  publicMap: (params: Record<string, unknown>) => ['public', 'map', params] as const,
  publicStats: ['public', 'stats'] as const,
  bills: ['bills'] as const,
  bill: (id: string) => ['bills', id] as const,
  payments: ['payments'] as const,
  announcements: ['announcements'] as const,
  announcementList: (params: Record<string, unknown>) => ['announcements', 'list', params] as const,
  notifications: ['notifications'] as const,
  notificationList: (params: Record<string, unknown>) => ['notifications', 'list', params] as const,
  unreadCount: ['notifications', 'unread'] as const,
  departments: ['departments'] as const,
  adminDepartments: ['admin', 'departments'] as const,
  adminAnalytics: (days: number) => ['admin', 'analytics', days] as const,
  adminUsers: (params: Record<string, unknown>) => ['admin', 'users', params] as const,
  adminAnnouncements: (params: Record<string, unknown>) => ['admin', 'announcements', params] as const,
  adminUtilities: ['admin', 'utilities'] as const,
  adminAudit: (params: Record<string, unknown>) => ['admin', 'audit', params] as const,
  adminSystem: ['admin', 'system'] as const,
  deptOverview: ['department', 'overview'] as const,
  deptHistory: (page: number) => ['department', 'history', page] as const,
  sessions: ['me', 'sessions'] as const,
};
